'use client';

// Image Studio: EVERY AI-generated visual in one prominent place, at the top
// of the dashboard. Create an image from a typed idea, see every draft's
// thumbnail at a glance, spot machine-verification results (✓ verified /
// ⚠ flagged), enlarge in a lightbox, and reroll with one click. All actions
// go through POST /api/drafts/image, so everything here is generated by the
// OpenAI image pipeline AND machine-verified — no unvetted visuals.

import { useCallback, useEffect, useRef, useState } from 'react';
import ProcessTracker, { makeSteps, stepActive, stepError, stepsDone, type ProcessStep } from '@/components/ProcessTracker';
import { announce, onRefresh, fetchDrafts } from '@/components/refreshBus';
import { useWorkspace } from '@/components/workspace';
import { PanelLoader } from '@/components/LoadingScreen';
import { friendlyError, friendlyImageError } from '@/lib/friendly-error';

// The visible pipeline a standalone image walks through — each step lights up
// as the real call behind it starts/finishes.
const IMG_STEPS = [
  { id: 'brief', label: 'Creating the image brief', detail: 'Saving an image draft for your idea…' },
  { id: 'image', label: 'Generating with OpenAI', detail: 'gpt-image-1 is painting your visual (~20s)…' },
  { id: 'verify', label: 'Machine verification', detail: 'A vision model confirms it is a text-free content image — any words/letters trigger an automatic regeneration…' },
  { id: 'gallery', label: 'Adding to the gallery', detail: 'Storing the verified image on the draft…' },
];

type Verification = {
  status: 'approved' | 'flagged' | 'unchecked';
  score: number | null;
  issues: string[];
  advisory?: string[];
  textDetected?: boolean;
};

type PackImage = {
  url: string;
  alt?: string;
  model?: string;
  variant?: number;
  verification?: Verification;
  source?: 'generated' | 'brand-card';
};

// Brand cards: the typographic slides painted by /api/drafts/card from the
// pack's own words, in the Brand Brain palette. One draft can hold a carousel.
type StoredCard = { url: string; index: number; headline: string; body?: string; kicker?: string; ground: string; width: number; height: number };
type PackCards = { createdAt: string; size: string; ground: string; standIn: boolean; slides: StoredCard[] };
type CardGround = 'paper' | 'pearl' | 'rust' | 'cocoa' | 'seal' | 'black' | 'photo';

type DraftLite = {
  id: string;
  topic?: string;
  pack?: { kind?: string; _image?: PackImage; _cards?: PackCards } & Record<string, unknown>;
};

function VerifyBadge({ v, size = 'sm' }: { v?: Verification; size?: 'sm' | 'lg' }) {
  const cls = size === 'lg' ? 'px-2.5 py-1 text-[12px]' : 'px-2 py-0.5 text-[10px]';
  if (v?.status === 'approved') {
    // Advisory notes (relevance, composition) ride on the tooltip and a small
    // count. They are worth a glance; they are not a warning.
    const notes = v.advisory || [];
    return (
      <span title={'Machine-verified' + (v.score != null ? ' · score ' + v.score + '/100' : '') + (notes.length ? ' · notes: ' + notes.join(' · ') : '')}
        className={'inline-flex items-center gap-1 rounded-full bg-emerald-600/90 font-semibold text-white ' + cls}>
        ✓ verified{notes.length ? <span className="font-normal opacity-80">· {notes.length} note{notes.length === 1 ? '' : 's'}</span> : null}
      </span>
    );
  }
  if (v?.textDetected) {
    return (
      <span title={(v.issues || []).join(' · ') || 'Text/letters detected — content images must be text-free. Reroll it.'}
        className={'inline-flex items-center gap-1 rounded-full bg-red-600/95 font-semibold text-white ' + cls}>
        ✗ text — reroll
      </span>
    );
  }
  if (v?.status === 'flagged') {
    return (
      <span title={(v.issues || []).join(' · ') || 'Flagged by the AI checker'}
        className={'inline-flex items-center gap-1 rounded-full bg-amber-500/95 font-semibold text-white ' + cls}>
        ⚠ flagged
      </span>
    );
  }
  return (
    <span title={(v?.issues || []).join(' · ') || 'Not auto-checked — review manually'}
      className={'inline-flex items-center gap-1 rounded-full bg-black/50 font-medium text-white ' + cls}>
      review
    </span>
  );
}

export default function ImageStudio() {
  const [drafts, setDrafts] = useState<DraftLite[]>([]);
  const [loading, setLoading] = useState(true);
  const [busyId, setBusyId] = useState<string | null>(null);
  const [quickTopic, setQuickTopic] = useState('');
  const workspace = useWorkspace();
  const [quickBusy, setQuickBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [lightbox, setLightbox] = useState<DraftLite | null>(null);
  // Brand cards for the draft open in the lightbox.
  const [cardGround, setCardGround] = useState<CardGround>('paper');
  const [cardSize, setCardSize] = useState<'portrait' | 'square' | 'landscape'>('portrait');
  const [cardBusy, setCardBusy] = useState<'carousel' | 'hero' | null>(null);
  const [cardNote, setCardNote] = useState<string | null>(null);
  const [proc, setProc] = useState<ProcessStep[] | null>(null);
  const procTimers = useRef<any[]>([]);
  function clearProcTimers() { procTimers.current.forEach((t) => clearTimeout(t)); procTimers.current = []; }
  function procAdvanceLater(id: string, ms: number) {
    procTimers.current.push(setTimeout(() => setProc((p) => (p ? stepActive(p, id) : p)), ms));
  }

  const load = useCallback(async (opts?: { quiet?: boolean }) => {
    if (!opts?.quiet) setLoading(true);
    try {
      // Shared with the clip pre-warmer, which asks for the same page on mount.
      // The .catch(() => ({})) here used to swallow the loader's own 401 message
      // and render the gallery's "No AI images yet" instead.
      const j = await fetchDrafts(50, 0);
      const list = Array.isArray((j as any)?.drafts) ? (j as any).drafts : [];
      setDrafts(list);
      setLoadError(null);
    } catch (e) { setLoadError(friendlyError(e, 'We could not load your images.')); }
    setLoading(false);
  }, []);


  useEffect(() => { void load(); }, [load]);

  // The studio follows whatever the rest of the dashboard is working on: pick
  // a keyword in Semrush or type a topic in the generator and it lands here,
  // instead of having to be retyped into this box.
  useEffect(() => {
    if (workspace.topic && !quickTopic) setQuickTopic(workspace.topic);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [workspace.topic]);

  // Interconnection: refresh the gallery whenever ANY panel announces new or
  // changed images/drafts (Content Generator packs, Autopilot hero images,
  // assistant drafts, deletions) — the studio shows every visual, live.
  useEffect(() => {
    return onRefresh((scopes) => {
      if (scopes.includes('images') || scopes.includes('drafts')) void load({ quiet: true });
    });
  }, [load]);

  // Clear any pending display timers if the component unmounts mid-run.
  useEffect(() => () => clearProcTimers(), []);

  const withImage = drafts.filter((d) => d?.pack?._image?.url);
  const missing = drafts.filter((d) => d?.id && !d?.pack?._image?.url && d?.pack?.kind !== 'clip').slice(0, 4);

  async function generateFor(id: string, regenerate: boolean) {
    if (busyId || quickBusy) return;
    setBusyId(id);
    setErr(null);
    clearProcTimers();
    setProc(stepActive(makeSteps(IMG_STEPS.slice(1)), 'image'));
    procAdvanceLater('verify', 22000);
    try {
      const r = await fetch('/api/drafts/image', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ id, regenerate }),
      });
      const j = await r.json().catch(() => ({}));
      clearProcTimers();
      if (!r.ok) throw new Error(j?.error || 'Image generation failed');
      setProc((p) => (p ? stepActive(p, 'gallery') : p));
      await load();
      setProc((p) => (p ? stepsDone(p) : p));
      announce('drafts', 'images', 'autopilot'); // new visual → library, galleries and Autopilot cards all update
      // Keep the lightbox in sync with the fresh image.
      if (lightbox && lightbox.id === id && j?.image?.url) {
        setLightbox({ ...lightbox, pack: { ...(lightbox.pack || {}), _image: j.image } });
      }
    } catch (e) {
      clearProcTimers();
      // Say why on the step itself, not just in the banner — a red cross under
      // "gpt-image-1 is painting your visual…" tells nobody anything. The same
      // sentence goes to the banner so the raw `openai images 429: {…}` body
      // never reaches a person.
      const why = friendlyImageError(e, 'The image could not be generated. The draft is unchanged.', {
        provider: 'openai',
        alsoSay: 'The draft is unchanged — only the picture failed.',
      });
      setProc((p) => (p ? stepError(p, undefined, why) : p));
      setErr(why);
    } finally {
      setBusyId(null);
    }
  }

  // Standalone creation: type an idea → an image-only draft is created and
  // sent through the same generate + verify pipeline as everything else.
  // Paint brand cards from the draft's words. 'carousel' makes one card per
  // paragraph; 'hero' makes a single cover card and sets it as the post image.
  async function makeCards(d: DraftLite, mode: 'carousel' | 'hero') {
    setCardBusy(mode); setErr(null); setCardNote(null);
    try {
      const body: Record<string, unknown> = { id: d.id, ground: cardGround, size: cardSize };
      if (mode === 'hero') { body.setHero = true; body.slides = [{ kicker: 'Cellular Institute', headline: String(d.topic || 'Cellular Institute') }]; }
      const r = await fetch('/api/drafts/card', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) });
      const j = await r.json().catch(() => ({}));
      if (!r.ok) { setErr(friendlyError(j?.message || j?.error || 'We could not draw the cards.', 'We could not draw the cards.')); return; }
      const nextPack = { ...(d.pack || {}), _cards: j.cards, ...(j.hero ? { _image: j.hero } : {}) };
      setDrafts((prev) => prev.map((x) => (x.id === d.id ? { ...x, pack: nextPack } : x)));
      setLightbox((lb) => (lb && lb.id === d.id ? { ...lb, pack: nextPack } : lb));
      if (j.note) setCardNote(String(j.note));
      else if (j.cards?.standIn) setCardNote('Drawn with stand-in type — add the Canela and Nexa files to public/fonts/brand for the final typefaces.');
      announce('drafts');
    } catch {
      setErr('We could not draw the cards just now.');
    } finally {
      setCardBusy(null);
    }
  }

  async function quickCreate() {
    const topic = quickTopic.trim();
    if (!topic || quickBusy || busyId) return;
    setQuickBusy(true);
    setErr(null);
    clearProcTimers();
    setProc(stepActive(makeSteps(IMG_STEPS), 'brief'));
    try {
      const dr = await fetch('/api/drafts', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ topic, pack: { kind: 'image', format: 'image' } }),
      });
      const dj = await dr.json().catch(() => ({}));
      const id = dj?.draft?.id;
      if (!dr.ok || !id) throw new Error(dj?.error || 'Could not create the image draft');
      setProc((p) => (p ? stepActive(p, 'image') : p));
      procAdvanceLater('verify', 22000); // generation ~20s inside one call, then the vision check
      const ir = await fetch('/api/drafts/image', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ id }),
      });
      const ij = await ir.json().catch(() => ({}));
      clearProcTimers();
      if (!ir.ok) throw new Error(ij?.error || 'Image generation failed');
      setProc((p) => (p ? stepActive(p, 'gallery') : p));
      setQuickTopic('');
      await load();
      setProc((p) => (p ? stepsDone(p) : p));
      announce('drafts', 'stats', 'images'); // new image draft → update library + counters everywhere
    } catch (e) {
      clearProcTimers();
      const why = friendlyImageError(e, 'The image could not be created. Try that idea again in a moment.', {
        provider: 'openai',
      });
      setProc((p) => (p ? stepError(p, undefined, why) : p));
      setErr(why);
    } finally {
      setQuickBusy(false);
    }
  }

  const lbImage = lightbox?.pack?._image;

  return (
    <section id="section-images" className="relative mb-8 overflow-hidden rounded-3xl bg-surface shadow-card ring-1 ring-line/60">
      <PanelLoader scope="image-studio" />
      <div className="flex flex-wrap items-center justify-between gap-x-6 gap-y-3 border-b border-line px-6 py-5 sm:px-8">
        <div className="min-w-0 flex-1 basis-72">
          <h2 className="flex flex-wrap items-center gap-2 text-[15px] font-semibold text-ink">
            <span className="rounded-full bg-accent/10 px-2 py-0.5 text-[11px] font-semibold uppercase tracking-wide text-accent">Step 2 · Images</span>
            🎨 AI Image Studio
            <span className="rounded-full bg-subtle px-2 py-0.5 text-[11px] font-medium text-ink-muted">
              every visual · generated + verified · one place
            </span>
          </h2>
          <p className="mt-0.5 text-[12px] text-ink-muted">
            Every image is a pure content image — no words, letters or logos, ever. Each one is created by the
            OpenAI image pipeline and machine-verified; anything with text is regenerated automatically.
            ✓ = verified text-free (a note count means the checker had an opinion, not a problem), ✗ = text slipped through (reroll it), ⚠ = a real defect found.
          </p>
        </div>
        <div className="flex w-full min-w-0 items-center gap-2 lg:w-auto">
          <input
            aria-label="Describe the image to create"
            value={quickTopic}
            onChange={(e) => setQuickTopic(e.target.value)}
            onBlur={(e) => { const v = e.target.value.trim(); if (v) workspace.setTopic(v, { source: 'images' }); }}
            onKeyDown={(e) => { if (e.key === 'Enter') void quickCreate(); }}
            placeholder="Describe an image… e.g. stem cell therapy for knees"
            className="min-w-0 flex-1 rounded-full bg-subtle px-4 py-2 text-[13px] text-ink ring-1 ring-line placeholder:text-ink-faint focus:ring-accent lg:w-72 lg:flex-none"
          />
          <button
            type="button"
            onClick={() => void quickCreate()}
            disabled={quickBusy || Boolean(busyId) || !quickTopic.trim()}
            className="shrink-0 rounded-full bg-accent px-4 py-2 text-[13px] font-medium text-white shadow-soft transition hover:opacity-90 disabled:opacity-50"
          >
            {quickBusy ? 'Creating…' : 'Create image'}
          </button>
        </div>
      </div>

      <div className="p-6 sm:p-8">
        {err && <div role="alert" className="mb-4 rounded-xl bg-red-50 px-4 py-2.5 text-[13px] text-red-700 ring-1 ring-red-100">{err}</div>}
        {proc && (
          <div className="mb-4">
            <ProcessTracker title="Creating your verified image" steps={proc} onClose={() => setProc(null)} />
          </div>
        )}

        {loading && <div className="text-[13px] text-ink-muted">Loading images…</div>}

        {!loading && withImage.length === 0 && !quickBusy && !proc && (
          <div className="rounded-2xl border border-dashed border-line p-8 text-center">
            <div className="text-[14px] font-medium text-ink-muted">{loadError ? 'We could not load your images' : 'No AI images yet'}</div>
            <div className="mt-1 text-[12px] text-ink-faint">
              {loadError || 'Type an idea above, or generate content below — every new pack gets a verified hero image automatically.'}
            </div>
          </div>
        )}

        {withImage.length > 0 && (
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
            {withImage.map((d) => {
              const img = d.pack!._image as PackImage;
              return (
                <button
                  key={d.id}
                  type="button"
                  onClick={() => setLightbox(d)}
                  className="group relative overflow-hidden rounded-2xl text-left ring-1 ring-line/60 transition hover:ring-black/20"
                  title={String(d.topic || 'AI image')}
                >
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={img.url} alt={img.alt || ''} className="aspect-square w-full object-cover transition group-hover:scale-[1.02]" />
                  <div className="absolute left-2 top-2 flex items-center gap-1">
                    <VerifyBadge v={img.verification} />
                    {img.source === 'brand-card' && <span className="rounded-full bg-[#9F4D27] px-2 py-0.5 text-[10px] font-semibold text-[#E0D2B7]">card</span>}
                  </div>
                  <div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent px-2.5 pb-2 pt-6">
                    <div className="truncate text-[11px] font-medium text-white">{String(d.topic || 'AI image')}</div>
                  </div>
                </button>
              );
            })}
          </div>
        )}

        {missing.length > 0 && (
          <div className="mt-5 flex flex-wrap items-center gap-2 rounded-2xl bg-subtle/50 px-4 py-3 ring-1 ring-line">
            <span className="text-[12px] font-medium text-ink-muted">Drafts without an image:</span>
            {missing.map((d) => (
              <button
                key={d.id}
                type="button"
                onClick={() => void generateFor(d.id, false)}
                disabled={Boolean(busyId) || quickBusy}
                className="rounded-full bg-white px-3 py-1 text-[12px] font-medium text-accent ring-1 ring-line transition hover:bg-subtle disabled:opacity-50"
              >
                {busyId === d.id ? 'Generating…' : '⚡ ' + String(d.topic || 'Untitled').slice(0, 40)}
              </button>
            ))}
          </div>
        )}
      </div>

      {/* Lightbox: full-size view + verification detail + one-click reroll. */}
      {lightbox && lbImage && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/85 p-4 sm:p-8"
          role="dialog"
          aria-modal="true"
          onClick={() => setLightbox(null)}
        >
          <div className="flex max-h-full max-w-4xl flex-col overflow-hidden rounded-2xl bg-surface shadow-2xl" onClick={(e) => e.stopPropagation()}>
            <div className="relative min-h-0 flex-1 bg-black">
              {busyId === lightbox.id && (
                <div className="absolute inset-0 z-10 flex items-center justify-center gap-2 bg-black/60 text-[14px] font-medium text-white">
                  <span className="h-4 w-4 animate-spin rounded-full border-2 border-white/40 border-t-white" />
                  Generating a new verified image…
                </div>
              )}
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={lbImage.url} alt={lbImage.alt || ''} className="max-h-[70vh] w-full object-contain" />
            </div>
            {/* Brand cards — the gallery's typographic slides, from this draft's own words. */}
            <div id="brand-cards" className="border-t border-line px-4 py-3">
              <div className="flex flex-wrap items-center gap-2">
                <span className="text-[12px] font-semibold text-ink">Brand cards</span>
                <select aria-label="Card colour" value={cardGround} onChange={(e) => setCardGround(e.target.value as CardGround)} className="rounded-full bg-subtle px-3 py-1 text-[12px] text-ink ring-1 ring-line">
                  <option value="paper">Paper</option>
                  <option value="pearl">Pearl</option>
                  <option value="rust">Rust</option>
                  <option value="cocoa">Cocoa</option>
                  <option value="seal">Seal brown</option>
                  <option value="black">Eerie black</option>
                  <option value="photo">Photo cover (this image)</option>
                </select>
                <select aria-label="Card size" value={cardSize} onChange={(e) => setCardSize(e.target.value as 'portrait' | 'square' | 'landscape')} className="rounded-full bg-subtle px-3 py-1 text-[12px] text-ink ring-1 ring-line">
                  <option value="portrait">1080×1350 · Instagram</option>
                  <option value="square">1080×1080 · Square</option>
                  <option value="landscape">1200×630 · LinkedIn</option>
                </select>
                <button type="button" onClick={() => void makeCards(lightbox, 'carousel')} disabled={Boolean(cardBusy) || busyId === lightbox.id}
                  className="rounded-full bg-[#9F4D27] px-3.5 py-1.5 text-[12px] font-medium text-[#E0D2B7] transition hover:opacity-90 disabled:opacity-50">
                  {cardBusy === 'carousel' ? 'Drawing…' : 'Make carousel from the caption'}
                </button>
                <button type="button" onClick={() => void makeCards(lightbox, 'hero')} disabled={Boolean(cardBusy) || busyId === lightbox.id}
                  className="rounded-full px-3.5 py-1.5 text-[12px] font-medium text-ink ring-1 ring-line transition hover:bg-subtle disabled:opacity-50">
                  {cardBusy === 'hero' ? 'Drawing…' : 'Cover card as post image'}
                </button>
                <span className="text-[11px] text-ink-faint">Words set by the dashboard in the brand palette — never drawn by the AI.</span>
              </div>
              {cardNote && <div role="status" className="mt-2 text-[11px] text-amber-700">{cardNote}</div>}
              {lightbox.pack?._cards?.slides?.length ? (
                <div className="mt-3 flex gap-2 overflow-x-auto pb-1">
                  {lightbox.pack._cards.slides.map((c) => (
                    <a key={c.index} href={c.url} target="_blank" rel="noopener noreferrer" title={c.headline} className="shrink-0 overflow-hidden rounded-lg ring-1 ring-line">
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img src={c.url} alt={c.headline} className="h-28 w-auto object-cover" />
                    </a>
                  ))}
                </div>
              ) : null}
            </div>
            <div className="flex flex-wrap items-center gap-2 border-t border-line px-4 py-3">
              <VerifyBadge v={lbImage.verification} size="lg" />
              <div className="min-w-0">
                <div className="truncate text-[13px] font-semibold text-ink">{String(lightbox.topic || 'AI image')}</div>
                {lbImage.verification?.issues?.length ? (
                  <div className="truncate text-[11px] text-amber-700">{lbImage.verification.issues.join(' · ')}</div>
                ) : (
                  <div className="text-[11px] text-ink-faint">{lbImage.model || 'OpenAI'} · attaches when this draft is scheduled or approved</div>
                )}
              </div>
              <div className="ml-auto flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => void generateFor(lightbox.id, true)}
                  disabled={busyId === lightbox.id}
                  className="rounded-full bg-accent px-4 py-1.5 text-[13px] font-medium text-white transition hover:opacity-90 disabled:opacity-50"
                >
                  {busyId === lightbox.id ? 'Working…' : '↻ New image'}
                </button>
                <a
                  href={lbImage.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="rounded-full px-4 py-1.5 text-[13px] font-medium text-ink ring-1 ring-line transition hover:bg-subtle"
                >
                  Full size
                </a>
                <button
                  type="button"
                  onClick={() => setLightbox(null)}
                  className="rounded-full px-4 py-1.5 text-[13px] font-medium text-ink-muted ring-1 ring-line transition hover:bg-subtle"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </section>
  );
}
