'use client';

// Image Studio: EVERY AI-generated visual in one prominent place, at the top
// of the dashboard. Create an image from a typed idea, see every draft's
// thumbnail at a glance, spot machine-verification results (✓ verified /
// ⚠ flagged), enlarge in a lightbox, and reroll with one click. All actions
// go through POST /api/drafts/image, so everything here is generated by the
// OpenAI image pipeline AND machine-verified — no unvetted visuals.

import { useCallback, useEffect, useRef, useState } from 'react';
import ProcessTracker, { makeSteps, stepActive, stepError, stepsDone, type ProcessStep } from '@/components/ProcessTracker';
import { announce, onRefresh, fetchDrafts } from '@/components/refreshBus';

// The visible pipeline a standalone image walks through — each step lights up
// as the real call behind it starts/finishes.
const IMG_STEPS = [
  { id: 'brief', label: 'Creating the image brief', detail: 'Saving an image draft for your idea…' },
  { id: 'image', label: 'Generating with OpenAI', detail: 'gpt-image-1 is painting your visual (~20s)…' },
  { id: 'verify', label: 'Machine verification', detail: 'A vision model checks for AI glitches — garbled text, warped anatomy, logos…' },
  { id: 'gallery', label: 'Adding to the gallery', detail: 'Storing the verified image on the draft…' },
];

type Verification = {
  status: 'approved' | 'flagged' | 'unchecked';
  score: number | null;
  issues: string[];
};

type PackImage = {
  url: string;
  alt?: string;
  model?: string;
  variant?: number;
  verification?: Verification;
};

type DraftLite = {
  id: string;
  topic?: string;
  pack?: { kind?: string; _image?: PackImage } & Record<string, unknown>;
};

function VerifyBadge({ v, size = 'sm' }: { v?: Verification; size?: 'sm' | 'lg' }) {
  const cls = size === 'lg' ? 'px-2.5 py-1 text-[12px]' : 'px-2 py-0.5 text-[10px]';
  if (v?.status === 'approved') {
    return (
      <span title={'Machine-verified' + (v.score != null ? ' · score ' + v.score + '/100' : '')}
        className={'inline-flex items-center gap-1 rounded-full bg-emerald-600/90 font-semibold text-white ' + cls}>
        ✓ verified
      </span>
    );
  }
  if (v?.status === 'flagged') {
    return (
      <span title={(v.issues || []).join(' · ') || 'Flagged by the AI checker'}
        className={'inline-flex items-center gap-1 rounded-full bg-amber-500/95 font-semibold text-white ' + cls}>
        ⚠ flagged
      </span>
    );
  }
  return (
    <span title={(v?.issues || []).join(' · ') || 'Not auto-checked — review manually'}
      className={'inline-flex items-center gap-1 rounded-full bg-black/50 font-medium text-white ' + cls}>
      review
    </span>
  );
}

export default function ImageStudio() {
  const [drafts, setDrafts] = useState<DraftLite[]>([]);
  const [loading, setLoading] = useState(true);
  const [busyId, setBusyId] = useState<string | null>(null);
  const [quickTopic, setQuickTopic] = useState('');
  const [quickBusy, setQuickBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  const [lightbox, setLightbox] = useState<DraftLite | null>(null);
  const [proc, setProc] = useState<ProcessStep[] | null>(null);
  const procTimers = useRef<any[]>([]);
  function clearProcTimers() { procTimers.current.forEach((t) => clearTimeout(t)); procTimers.current = []; }
  function procAdvanceLater(id: string, ms: number) {
    procTimers.current.push(setTimeout(() => setProc((p) => (p ? stepActive(p, id) : p)), ms));
  }

  const load = useCallback(async () => {
    try {
      // Shared with the clip pre-warmer, which asks for the same page on mount.
      const j = await fetchDrafts(50, 0).catch(() => ({}));
      const list = Array.isArray((j as any)?.drafts) ? (j as any).drafts : [];
      setDrafts(list);
    } catch { /* transient */ }
    setLoading(false);
  }, []);

  useEffect(() => { void load(); }, [load]);

  // Interconnection: refresh the gallery whenever ANY panel announces new or
  // changed images/drafts (Content Generator packs, Autopilot hero images,
  // assistant drafts, deletions) — the studio shows every visual, live.
  useEffect(() => {
    return onRefresh((scopes) => {
      if (scopes.includes('images') || scopes.includes('drafts')) void load();
    });
  }, [load]);

  // Clear any pending display timers if the component unmounts mid-run.
  useEffect(() => () => clearProcTimers(), []);

  const withImage = drafts.filter((d) => d?.pack?._image?.url);
  const missing = drafts.filter((d) => d?.id && !d?.pack?._image?.url && d?.pack?.kind !== 'clip').slice(0, 4);

  async function generateFor(id: string, regenerate: boolean) {
    if (busyId || quickBusy) return;
    setBusyId(id);
    setErr(null);
    clearProcTimers();
    setProc(stepActive(makeSteps(IMG_STEPS.slice(1)), 'image'));
    procAdvanceLater('verify', 22000);
    try {
      const r = await fetch('/api/drafts/image', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ id, regenerate }),
      });
      const j = await r.json().catch(() => ({}));
      clearProcTimers();
      if (!r.ok) throw new Error(j?.error || 'Image generation failed');
      setProc((p) => (p ? stepActive(p, 'gallery') : p));
      await load();
      setProc((p) => (p ? stepsDone(p) : p));
      announce('drafts'); // draft now carries an image → refresh the library view
      // Keep the lightbox in sync with the fresh image.
      if (lightbox && lightbox.id === id && j?.image?.url) {
        setLightbox({ ...lightbox, pack: { ...(lightbox.pack || {}), _image: j.image } });
      }
    } catch (e) {
      clearProcTimers();
      setProc((p) => (p ? stepError(p) : p));
      setErr(e instanceof Error ? e.message : 'Image generation failed');
    } finally {
      setBusyId(null);
    }
  }

  // Standalone creation: type an idea → an image-only draft is created and
  // sent through the same generate + verify pipeline as everything else.
  async function quickCreate() {
    const topic = quickTopic.trim();
    if (!topic || quickBusy || busyId) return;
    setQuickBusy(true);
    setErr(null);
    clearProcTimers();
    setProc(stepActive(makeSteps(IMG_STEPS), 'brief'));
    try {
      const dr = await fetch('/api/drafts', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ topic, pack: { kind: 'image', format: 'image' } }),
      });
      const dj = await dr.json().catch(() => ({}));
      const id = dj?.draft?.id;
      if (!dr.ok || !id) throw new Error(dj?.error || 'Could not create the image draft');
      setProc((p) => (p ? stepActive(p, 'image') : p));
      procAdvanceLater('verify', 22000); // generation ~20s inside one call, then the vision check
      const ir = await fetch('/api/drafts/image', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ id }),
      });
      const ij = await ir.json().catch(() => ({}));
      clearProcTimers();
      if (!ir.ok) throw new Error(ij?.error || 'Image generation failed');
      setProc((p) => (p ? stepActive(p, 'gallery') : p));
      setQuickTopic('');
      await load();
      setProc((p) => (p ? stepsDone(p) : p));
      announce('drafts', 'stats'); // new image draft → update library + counters everywhere
    } catch (e) {
      clearProcTimers();
      setProc((p) => (p ? stepError(p) : p));
      setErr(e instanceof Error ? e.message : 'Image creation failed');
    } finally {
      setQuickBusy(false);
    }
  }

  const lbImage = lightbox?.pack?._image;

  return (
    <section id="section-images" className="mb-8 overflow-hidden rounded-3xl bg-surface shadow-card ring-1 ring-line/60">
      <div className="flex flex-wrap items-center justify-between gap-x-6 gap-y-3 border-b border-line px-6 py-5 sm:px-8">
        <div className="min-w-0 flex-1 basis-72">
          <h2 className="flex flex-wrap items-center gap-2 text-[15px] font-semibold text-ink">
            🎨 AI Image Studio
            <span className="rounded-full bg-subtle px-2 py-0.5 text-[11px] font-medium text-ink-muted">
              every visual · generated + verified · one place
            </span>
          </h2>
          <p className="mt-0.5 text-[12px] text-ink-muted">
            Each image is created by the OpenAI image pipeline and machine-checked for AI glitches
            (garbled text, warped anatomy, logos) before you ever attach it. ✓ = verified clean, ⚠ = the checker found issues.
          </p>
        </div>
        <div className="flex w-full min-w-0 items-center gap-2 lg:w-auto">
          <input
            aria-label="Describe the image to create"
            value={quickTopic}
            onChange={(e) => setQuickTopic(e.target.value)}
            onKeyDown={(e) => { if (e.key === 'Enter') void quickCreate(); }}
            placeholder="Describe an image… e.g. stem cell therapy for knees"
            className="min-w-0 flex-1 rounded-full bg-subtle px-4 py-2 text-[13px] text-ink ring-1 ring-line placeholder:text-ink-faint focus:ring-accent lg:w-72 lg:flex-none"
          />
          <button
            type="button"
            onClick={() => void quickCreate()}
            disabled={quickBusy || Boolean(busyId) || !quickTopic.trim()}
            className="shrink-0 rounded-full bg-accent px-4 py-2 text-[13px] font-medium text-white shadow-soft transition hover:opacity-90 disabled:opacity-50"
          >
            {quickBusy ? 'Creating…' : 'Create image'}
          </button>
        </div>
      </div>

      <div className="p-6 sm:p-8">
        {err && <div role="alert" className="mb-4 rounded-xl bg-red-50 px-4 py-2.5 text-[13px] text-red-700 ring-1 ring-red-100">{err}</div>}
        {proc && (
          <div className="mb-4">
            <ProcessTracker title="Creating your verified image" steps={proc} onClose={() => setProc(null)} />
          </div>
        )}

        {loading && <div className="text-[13px] text-ink-muted">Loading images…</div>}

        {!loading && withImage.length === 0 && !quickBusy && !proc && (
          <div className="rounded-2xl border border-dashed border-line p-8 text-center">
            <div className="text-[14px] font-medium text-ink-muted">No AI images yet</div>
            <div className="mt-1 text-[12px] text-ink-faint">
              Type an idea above, or generate content below — every new pack gets a verified hero image automatically.
            </div>
          </div>
        )}

        {withImage.length > 0 && (
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
            {withImage.map((d) => {
              const img = d.pack!._image as PackImage;
              return (
                <button
                  key={d.id}
                  type="button"
                  onClick={() => setLightbox(d)}
                  className="group relative overflow-hidden rounded-2xl text-left ring-1 ring-line/60 transition hover:ring-black/20"
                  title={String(d.topic || 'AI image')}
                >
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={img.url} alt={img.alt || ''} className="aspect-square w-full object-cover transition group-hover:scale-[1.02]" />
                  <div className="absolute left-2 top-2"><VerifyBadge v={img.verification} /></div>
                  <div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent px-2.5 pb-2 pt-6">
                    <div className="truncate text-[11px] font-medium text-white">{String(d.topic || 'AI image')}</div>
                  </div>
                </button>
              );
            })}
          </div>
        )}

        {missing.length > 0 && (
          <div className="mt-5 flex flex-wrap items-center gap-2 rounded-2xl bg-subtle/50 px-4 py-3 ring-1 ring-line">
            <span className="text-[12px] font-medium text-ink-muted">Drafts without an image:</span>
            {missing.map((d) => (
              <button
                key={d.id}
                type="button"
                onClick={() => void generateFor(d.id, false)}
                disabled={Boolean(busyId) || quickBusy}
                className="rounded-full bg-white px-3 py-1 text-[12px] font-medium text-accent ring-1 ring-line transition hover:bg-subtle disabled:opacity-50"
              >
                {busyId === d.id ? 'Generating…' : '⚡ ' + String(d.topic || 'Untitled').slice(0, 40)}
              </button>
            ))}
          </div>
        )}
      </div>

      {/* Lightbox: full-size view + verification detail + one-click reroll. */}
      {lightbox && lbImage && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/85 p-4 sm:p-8"
          role="dialog"
          aria-modal="true"
          onClick={() => setLightbox(null)}
        >
          <div className="flex max-h-full max-w-4xl flex-col overflow-hidden rounded-2xl bg-surface shadow-2xl" onClick={(e) => e.stopPropagation()}>
            <div className="relative min-h-0 flex-1 bg-black">
              {busyId === lightbox.id && (
                <div className="absolute inset-0 z-10 flex items-center justify-center gap-2 bg-black/60 text-[14px] font-medium text-white">
                  <span className="h-4 w-4 animate-spin rounded-full border-2 border-white/40 border-t-white" />
                  Generating a new verified image…
                </div>
              )}
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={lbImage.url} alt={lbImage.alt || ''} className="max-h-[70vh] w-full object-contain" />
            </div>
            <div className="flex flex-wrap items-center gap-2 border-t border-line px-4 py-3">
              <VerifyBadge v={lbImage.verification} size="lg" />
              <div className="min-w-0">
                <div className="truncate text-[13px] font-semibold text-ink">{String(lightbox.topic || 'AI image')}</div>
                {lbImage.verification?.issues?.length ? (
                  <div className="truncate text-[11px] text-amber-700">{lbImage.verification.issues.join(' · ')}</div>
                ) : (
                  <div className="text-[11px] text-ink-faint">{lbImage.model || 'OpenAI'} · attaches when this draft is scheduled or approved</div>
                )}
              </div>
              <div className="ml-auto flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => void generateFor(lightbox.id, true)}
                  disabled={busyId === lightbox.id}
                  className="rounded-full bg-accent px-4 py-1.5 text-[13px] font-medium text-white transition hover:opacity-90 disabled:opacity-50"
                >
                  {busyId === lightbox.id ? 'Working…' : '↻ New image'}
                </button>
                <a
                  href={lbImage.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="rounded-full px-4 py-1.5 text-[13px] font-medium text-ink ring-1 ring-line transition hover:bg-subtle"
                >
                  Full size
                </a>
                <button
                  type="button"
                  onClick={() => setLightbox(null)}
                  className="rounded-full px-4 py-1.5 text-[13px] font-medium text-ink-muted ring-1 ring-line transition hover:bg-subtle"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </section>
  );
}
